/// Flutter icons MyNewIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyNewIcon
///      fonts:
///       - asset: fonts/MyNewIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyNewIcon {
  MyNewIcon._();

  static const _kFontFam = 'MyNewIcon';
  static const String? _kFontPkg = null;

  static const IconData fast_food = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
